FROM n8nio/n8n

ARG DB_POSTGRESDB_PASSWORD
ARG DB_POSTGRESDB_HOST
ARG DB_POSTGRESDB_PORT
ARG DB_POSTGRESDB_DATABASE
ARG DB_POSTGRESDB_USER

ARG N8N_USERNAME
ARG N8N_PASSWORD

ARG N8N_ENCRYPTION_KEY

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$DB_POSTGRESDB_DATABASE
ENV DB_POSTGRESDB_HOST=$DB_POSTGRESDB_HOST
ENV DB_POSTGRESDB_PORT=$DB_POSTGRESDB_PORT
ENV DB_POSTGRESDB_USER=$DB_POSTGRESDB_USER
ENV DB_POSTGRESDB_PASSWORD=$DB_POSTGRESDB_PASSWORD

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$N8N_USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$N8N_PASSWORD
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY

ENV ENABLE_ALPINE_PRIVATE_NETWORKING=true

USER node

COPY ./workflows ./workflows
COPY ./credentials ./credentials

RUN mkdir -p ~/.n8n/nodes

RUN cd ~/.n8n/nodes && \
    npm install --production --force n8n-nodes-browserless n8n-nodes-evolution-api n8n-nodes-globals

RUN n8n import:workflow --separate --input=./workflows/
RUN n8n update:workflow --all --active=true
# RUN n8n import:credentials --separate --input=./credentials

CMD ["n8n", "start"]
